# Generated by Django 5.1.6 on 2025-03-04 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=45)),
                ('delete', models.CharField(choices=[('delete', 'Delete'), ('ondelete', 'Ondelete')], default='delete', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=45)),
                ('delete', models.CharField(choices=[('delete', 'Delete'), ('ondelete', 'Ondelete')], default='delete', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=45)),
                ('delete', models.CharField(choices=[('delete', 'Delete'), ('ondelete', 'Ondelete')], default='delete', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('JR', 'Junior'), ('MD', 'Mid-level'), ('SR', 'Senior'), ('LD', 'Lead'), ('EX', 'Executive')], default='JR', max_length=2)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=45)),
                ('delete', models.CharField(choices=[('delete', 'Delete'), ('ondelete', 'Ondelete')], default='delete', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('brithday', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=200)),
                ('send', models.CharField(choices=[('NEW', 'Yangi'), ('IN_REVIEW', 'Ko‘rib chiqilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='NEW', max_length=20)),
                ('senddata', models.DateTimeField(auto_now_add=True)),
                ('sendstatus', models.CharField(choices=[('NEW', 'Yangi'), ('IN_REVIEW', 'Ko‘rib chiqilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.CharField(choices=[('publish', 'Published'), ('draf', 'Draf')], default='publish', max_length=45)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=45)),
                ('delete', models.CharField(choices=[('delete', 'Delete'), ('ondelete', 'Ondelete')], default='delete', max_length=45)),
                ('employee', models.ManyToManyField(related_name='Employees', to='fileflow.employee')),
                ('friend', models.ManyToManyField(related_name='Friend', to='fileflow.friend')),
                ('partner', models.ManyToManyField(related_name='Partner', to='fileflow.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el1', models.DecimalField(decimal_places=4, max_digits=20)),
                ('el2', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fileflow.person')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileflow.position'),
        ),
    ]
